### PR TITLE
Code review request

### PR DESCRIPTION
**Pull request by shjang7**
This project requirement is implementation for 6 examples only, 
but I implemented 35 examples to check for every corner cases. 
So, please consider this for reviewing.
Thank you.

### CODE REVIEW

**Comment by dipto0321** [comment]
# Awesome 👏 🏆 

Hi @shjang7 ,

This project was awesome. I liked that in that project testing it covers all the possible cases. For this 🥇 . Just a minor change needed which is all about the better way to assign variables in `RSpec`. It will be better if [this](https://github.com/shjang7/enumerable-method-rspec/blob/11abf276d81e9948a91d6b0455328d501a8f4f09/spec/enumerable_spec.rb#L18) is written by 👇 way : 

```ruby
let(:range) { (1..4) }
``` 

After applying this small fix in every place where this test cases assigned variables like `range = (1..4)` send another request to re-review this project.

Thanks 🙏

**Comment by shjang7** [comment]
Yes. I agree with using 'let' for rspec. 
I have changed those part to use 'let'. 
I would ask you review again updated code. 
Thank you.

**Comment by dipto0321** [comment]
# Awesome 👏 💯 

Hi @shjang7 ,

This is nice! Our mission completed 😄 . Just a simple tip for arranging code. It would be better if all those `let` will together in one place inside the describe. You can do this before merging this project into the master. This is from me 👍 

Thanks 🙏 😌

**Comment by shjang7** [comment]
Thank you  @dipto0321 
After moving all the assigning to the top, it becomes more clean code.
I will merge with this. Thank you.

**Pull request merged**
